version: '3'
services:
       web:
          build: .
          ports:
            - "5000:5000"
          volumes:
            - .:/code
       mariadb:
         image: mariadb
         environment:
           MARIADB_ROOT_PASSWORD: password
